# Databricks notebook source
# MAGIC %md
# MAGIC # 07 - Auto-generate Incident Report (Postmortem Draft)
# MAGIC Scene 5: Generate Postmortem Draft -> Slack/Confluence format

# COMMAND ----------

# MAGIC %md
# MAGIC ## Generate report draft from gold_anomaly + root-cause conclusions
# MAGIC Input can come from 06_rca_agent output or manual; here using placeholder + template

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Anomaly window summary
# MAGIC SELECT min(bucket_5m) AS window_start, max(bucket_5m) AS window_end,
# MAGIC   sum(impact_estimated) AS estimated_impact
# MAGIC FROM cursor_gaming.gaming.gold_anomaly
# MAGIC WHERE is_anomaly = true;

# COMMAND ----------

# Report template (Slack/Confluence style)
INCIDENT_REPORT_TEMPLATE = """
# Incident Postmortem (Draft)

## 1. What happened
Payment success rate and revenue dropped significantly during **{window_start} ~ {window_end}** (UTC). Anomaly auto-detected (gold_anomaly, z_score < -3). Estimated impact: {estimated_impact}.

## 2. Impact
- Metrics: payment success rate, revenue
- Estimated loss/impact: see above
- Affected users: DAU share in anomaly window (see dashboard)

## 3. Root causes
{root_causes}

## 4. Mitigation
{mitigation}

## 5. Follow-up
{follow_up}

## 6. Owner & Timeline
- Owner: [fill]
- Detected: {window_start}
- Resolved: [fill]
- Report generated: {report_ts}
---
*Draft generated by LiveOps GenAI; please review before publishing.*
"""

# COMMAND ----------

from datetime import datetime

# Placeholder: in production get from RCA Agent output or parameters
root_causes = """
- **Root cause #1**: iOS + app_version 1.2.7 + SG payment failure rate 2%->18% (evidence: gold_kpi_5m, dimensions platform/app_version/region)
- **Root cause #2**: error_code=TOKEN_EXPIRED spike (evidence: silver_payments error_code counts)
- **Root cause #3**: payment_provider=Stripe on iOS new version failure rate anomaly (evidence: gold_kpi_5m provider slice)
"""
mitigation = "Rollback iOS 1.2.7 / or canary off payment for that version; force token refresh; contact Stripe to investigate."
follow_up = "Fix TOKEN refresh logic in 1.2.7; align with Stripe iOS SDK; add payment success rate alerting and auto RCA."

# In production: read window_start, window_end, estimated_impact from query result above (spark)
window_start = "2025-03-04 10:05:00"
window_end   = "2025-03-04 10:40:00"
estimated_impact = "See dashboard anomaly summary"
report_ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

report = INCIDENT_REPORT_TEMPLATE.format(
    window_start=window_start,
    window_end=window_end,
    estimated_impact=estimated_impact,
    root_causes=root_causes,
    mitigation=mitigation,
    follow_up=follow_up,
    report_ts=report_ts,
)

# COMMAND ----------

print(report)

# COMMAND ----------

# MAGIC %md
# MAGIC You can write `report` to Confluence / Slack or copy to clipboard; optionally polish with GenAI.
